### ISSUE TITLE
Deployment flag not working as intended

### ISSUE THREAD

**Issue by RachitBhargava99** [nodeshift/nodeshift#481]
The flag added in v7.1.0 (`useDeployment`) does not seem to work as intended. I get the following error when using it.

```
ERROR Deployment.apps "<app-name>" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"thinktank", "chart":"ibm-cem", "component":"thinktank", "deploymentconfig":"<app-name>", "heritage":"Tiller", "origin":"helm-cem", "project":"<app-name>", "provider":"nodeshift", "release":"rachit", "version":"1.0.0"}: `selector` does not match template `labels`
ERROR Status code 422
```

**Comment by lholmquist** [comment]
How are you using it?   Are you using a already defined deployment yaml?  if so,  would you be able to share some of it?

**Comment by RachitBhargava99** [comment]
I am using it through the `useDeployment` flag. I do have an already-defined deployment yml. What fields are you looking for?

**Comment by lholmquist** [comment]
that error is saying that there is something wrong(an invalid value) with the labels in "spec.template.metadata.labels"

It looks like the app name is called "<app-name>" which could be an issue.

This error is actually happening on Openshift when trying to apply the deployment

**Comment by RachitBhargava99** [comment]
Here's what I have in `spec.template.metadata`.

```
      labels:
        app: ibm-cem
        chart: ibm-cem
        component: thinktank
        heritage: Tiller
        origin: helm-cem
        release: rachit
```

Pushing the changes in manually does not really produce an error.
